INSERT INTO Movies (MovieID, MovieName, MovieDescription, MoviePoster, NS1, NS2, SS1, SS2)
VALUES ('1',
        'Titanic',
        '"Titanic" is a 1997 epic romance and disaster film directed by James Cameron. Starring Leonardo DiCaprio and Kate Winslet, the movie is set against the backdrop of the ill-fated RMS Titanic maiden voyage in 1912.It tells the story of a forbidden love affair between two passengers from different social classes.',
        'TitanicPoster',
        'Showtime 1 - 5:00 PM',
        'Showtime 2 - 7:50 PM',
        'Showtime 1 - 11:00 AM',
        'Showtime 2 - 6:00 PM'),
       ('2',
       'Avatar',
       "'Avatar' is a 2009 science fiction film directed by James Cameron. It is set in the mid-22nd century on the fictional planet of Pandora and follows a paraplegic ex-Marine who becomes part of the Avatar Program. Through his avatar, he forms a connection with the indigenous Na'vi people and becomes torn between following orders and protecting their way of life. The film is known for its groundbreaking use of 3D technology and is one of the highest-grossing movies of all time.",
       'AvatarPoster',
        'Showtime 1 - 10:50 AM',
        'Showtime 2 - 11:50 AM',
        'Showtime 1 - 4:00 PM',
        'Showtime 2 - 6:00 PM'),
       ('3',
       'Inception',
       "'Inception' is a 2010 mind-bending thriller directed by Christopher Nolan. The film revolves around the concept of entering people's dreams to steal their secrets or plant ideas into their minds. It follows a skilled thief who must navigate a complex web of dreams within dreams. 'Inception' is known for its intricate plot, stunning visuals, and thought-provoking exploration of the nature of reality and dreams.",
       'InceptionPoster',
        'Showtime 1 - 10:50 AM',
        'Showtime 2 - 11:50 AM',
        'Showtime 1 - 4:00 PM',
        'Showtime 2 - 6:00 PM');